#!/bin/bash
#
# config: 23 20
#
# 23 = User dump(2), elog dump(3)
# 20 = priority

# @brief: Collect the PEL files

# shellcheck disable=SC1091
. "$DREPORT_INCLUDE"/functions

dir="/var/lib/phosphor-logging/extensions/pels/logs"
desc="PEL Files"
if [ -d $dir ]; then
    add_copy_file "$dir" "$desc"
fi
