#!/usr/bin/env bash
#
# config: 2 50
# @brief: Collect VPD persistent data
#

. $DREPORT_INCLUDE/functions

file_name="/var/lib/vpd"
desc="VPD persistent data"

if [ -d "$file_name" ]; then
    add_copy_file "$file_name" "$desc"
else
    log_info "No $desc data"
fi

desc="Bad VPD"
dir_name="/tmp/bad-vpd"

if [ -f $dir_name ]; then
    add_copy_file "$dir_name" "$desc"
else
    log_info "No $desc data"
fi
