#!/usr/bin/env bash
#
# config: 23 25
# @brief: Collect VPD persistent data
#

. $DREPORT_INCLUDE/functions

file_name="/var/lib/vpd"
desc="VPD persistent data"

if [ -d "$file_name" ]; then
    add_copy_file "$file_name" "$desc"
fi
