#!/usr/bin/env bash

#CONSTANTS
declare -rx TRUE=1
declare -rx FALSE=0
declare -rx TIME_STAMP="date -u"
declare -rx UNLIMITED="unlimited"
declare -rx DREPORT_INCLUDE="$DREPORT_SOURCE/include.d"
declare -rx HEADER_EXTENSION="$DREPORT_INCLUDE/gendumpheader"
declare -rx CUSTOM_PACKAGING="$DREPORT_INCLUDE/package"
declare -rx INVENTORY_MANAGER='xyz.openbmc_project.Inventory.Manager'
declare -rx INVENTORY_PATH='/xyz/openbmc_project/inventory/system'
declare -rx INVENTORY_ASSET_INT='xyz.openbmc_project.Inventory.Decorator.Asset'
declare -rx INVENTORY_BMC_BOARD='/xyz/openbmc_project/inventory/system/chassis/motherboard'

#Error Codes
declare -rx SUCCESS="0"
declare -rx INTERNAL_FAILURE="1"
declare -rx RESOURCE_UNAVAILABLE="2"

#VARIABLES
declare -x EPOCHTIME
EPOCHTIME=$(date +"%s")
declare -x name=""
declare -x dump_dir="/tmp"
declare -x dump_id="00000000"
declare -x dump_size="unlimited"
declare -x optional_path=""
declare -x name_dir=""
declare -x quiet=$FALSE
declare -x verbose=$FALSE
declare -x serialNo="0000000"
declare -x dDay=$(date -d @$EPOCHTIME +'%Y%m%d%H%M%S')

# @brief get serial number property from inventory
function fetch_serial_number () {
    serialNo=$(busctl get-property $INVENTORY_MANAGER $INVENTORY_PATH \
        $INVENTORY_ASSET_INT SerialNumber | cut -d " " -f 2 | sed "s/^\(\"\)\(.*\)\1\$/\2/g")

    if [ -z "$serialNo" ]; then
        serialNo="0000000"
    fi
}

# @brief validate_arg function, will validate the provided arguments
function validate_arg () {
    # shellcheck disable=SC2181
    if [ $? -ne 0 ]
    then
        echo "Error: Invalid options"
        exit 1
    fi
    # shellcheck disable=SC2181
    eval set -- "$TEMP"
    while [[ $# -gt 1 ]]; do
        key="$1"
        case $key in
            -n|--name)
                name=$2
                dump_content_type=$name
                shift 2;;
            -d|--dir)
                dump_dir=$2
                shift 2;;
            -i|--dumpid)
                dump_id=$2
                shift 2;;
            -t|--type)
                # shellcheck disable=SC2034  # varibale comes from elsewhere.
                dump_type=$2
                shift 2;;
            -p|--path)
                optional_path=$2
                shift 2;;
            -s|--size)
                dump_size=$2
                shift 2;;
            -v|—-verbose)
                verbose=$TRUE
                shift;;
            -q|—-quiet)
                quiet=$TRUE
                shift;;
            -V|--version)
                shift;;
            -h|--help)
                # shellcheck disable=SC2034  # varibale comes from elsewhere.
                echo "$help"
                exit;;
            *) # unknown option
                echo "Unknown argument: $1"
                echo  "$help"
                exit 1;;
        esac
    done
}

fetch_serial_number
