#! /bin/bash

help=$"
        openpower_dump creates an archive(gz compressed) consisting of the following:
                * hostboot dump files and header applied on top of it
        The type parameter controls the content of the data. The generated
        archive is stored in the user specified location.

usage: openpower_dump [OPTION]

Options:
        -n, —-name <name>     Name to be used for the archive.
                              Default name format <name>_<dump_id>_<epochtime>
        -d, —-dir <directory> Archive directory to copy the compressed report.
                              Default output directory is /tmp
        -i, —-id <id>         Dump identifier to associate with the archive.
                              Identifiers include numeric characters.
                              Default dump identifier is 0
        -p, —-path <path>     Optional contents to be included in the archive.
                              Valid paths are absolute file path.
        -h, —-help            Display this help and exit.
"

#CONSTANTS
declare -rx EPOCHTIME=$(date +"%s")
declare -rx TIME_STAMP="date -u"
declare -rx DREPORT_SOURCE="/usr/share/dreport.d"
declare -rx DREPORT_INCLUDE="$DREPORT_SOURCE/include.d"
declare -rx HEADER_EXTENSION="$DREPORT_INCLUDE/gendumpheader"
declare -rx TYPE_HOSTBOOT="hostboot"

#Error Codes
declare -rx SUCCESS="0"
declare -rx INTERNAL_FAILURE="1"
declare -rx RESOURCE_UNAVAILABLE="2"

#VARIABLES
declare -x name=""
declare -x dump_dir=""
declare -x dump_id="00000000"
declare -x dump_type=$TYPE_HOSTBOOT
declare -x optional_path=""
declare -x size_dump=""
declare -x eid_dir=""
declare -x elog_id=""

# @brief Check the validity of user inputs and initialize global
#        variables.
# @return 0 on success, error code otherwise

function initialize()
{
    #Dump file name
    if [ -z $name ]; then
        name=$"hbdump_"$dump_id"_$EPOCHTIME"
    else
        name="${name}_${dump_id}_${EPOCHTIME}"
    fi

    #Source files path
    if [ -z $optional_path ]; then
        echo "Error: Source file path is not provided."
        return $RESOURCE_UNAVAILABLE;
    fi

    #Destination path
    if [ -z $dump_dir ]; then
        echo "Error: Destination path is not provided."
        return $RESOURCE_UNAVAILABLE;
    fi

    return $SUCCESS
}

# @brief Packaging the dump and transferring to dump location.
function package()
{
    mkdir -p "$dump_dir"
    if [ $? -ne 0 ]; then
        log_error "Could not create the destination directory $dump_dir"
    fi

    cd $optional_path
    
    eid_dir=$(find $optional_path -type f -name ErrorLog)
    if [ $? -ne 0 ]; then
        echo "Could not find ErrorLog file"
    else
        elog_id=$(cut -d' ' -f1 "$eid_dir")
    fi

    tar -cvzf $name.tar plat_dump/*Sbe*
    if [ $? -ne 0 ]; then
        echo $($TIME_STAMP) "Could not create the compressed tar file"
        return $INTERNAL_FAILURE
    fi

    size_dump=$(ls -al $name.tar | awk '{print $5}')
    echo "Adding Dump Header :"$HEADER_EXTENSION
    ("$HEADER_EXTENSION")
    gzip -c "/tmp/dumpheader_$EPOCHTIME" "$name.tar" > "$name.tar.gz"
    mv $name.tar.gz $dump_dir

    if [ $? -ne 0 ]; then
        echo $($TIME_STAMP) "Could not create the compressed tar file"
        rm -rf "$name.tar" "/tmp/dumpheader_$EPOCHTIME"
        return $INTERNAL_FAILURE
    fi

    rm -rf "/tmp/dumpheader_$EPOCHTIME" "$name.tar"
    rm -rf $optional_path

    return $SUCCESS
}

# @brief Main function
function main()
{
    #initialize the global variables and checks for user provided data
    initialize
    result=$?
    if [[ ${result} -ne $SUCCESS ]]; then
        echo $($TIME_STAMP) "Error: Failed to initialize, Exiting"
        exit;
    fi

    package  #package the dump
    result=$?
    if [[ ${result} -ne $SUCCESS ]]; then
        echo $($TIME_STAMP) "Error: Failed to package, Exiting"
    else
        echo $($TIME_STAMP) "Successfully completed"
        exit;
    fi
}

TEMP=`getopt -o n:d:i:p:h \
      --long name:,dir:,dumpid:,path:,help \
      -- "$@"`

if [ $? -ne 0 ]
then
    echo "Error: Invalid options"
    exit 1
fi

eval set -- "$TEMP"

while [[ $# -gt 1 ]]; do
    key="$1"
    case $key in
        -n|--name)
            name=$2
            shift 2;;
        -d|--dir)
            dump_dir=$2
            shift 2;;
        -i|--dumpid)
            dump_id=$2
            shift 2;;
        -p|--path)
            optional_path=$2
            shift 2;;
        -h|--help)
            echo "$help"
            exit;;
        *) # unknown option
            echo "Unknown argument: $1"
            echo  "$help"
            exit 1;;
    esac
done

main #main program
exit $?
