#!/usr/bin/env bash
#
# config: 234 10
# @brief: Add CFAM details to dump.
#

. "$DREPORT_INCLUDE/functions"

# shellcheck source=./power-target.sh
source /etc/profile.d/power-target.sh

file_name="cfam.log"
if [ -e "/usr/bin/edbg" ]; then
    desc="cfam 283c"
    command="/usr/bin/edbg getcfam pu 283c -pall"
    add_cmd_output "$command" "$file_name" "$desc"

    desc="cfam 1007"
    command="/usr/bin/edbg getcfam pu 1007 -pall"
    add_cmd_output "$command" "$file_name" "$desc"

    desc="cfam 2809"
    command="/usr/bin/edbg getcfam pu 2809 -pall"
    add_cmd_output "$command" "$file_name" "$desc"
fi
