#!/bin/bash
#
# config: 234 40
# @brief: Collect GUARD record information.
#

. $DREPORT_INCLUDE/functions

desc="GUARD Records"
file_name="/var/lib/phosphor-software-manager/hostfw/running/GUARD"

# Check file is present and not empty.
if [ ! -s "$file_name" ]; then
    log_info "No $desc"
    exit 0
fi

add_copy_file "$file_name" "$desc"

# collect guarded list
guard_log_file=guard.log
if [ -e "/usr/bin/guard" ]; then
    add_cmd_output "echo $'\n[Guard List]'" "$guard_log_file" "guard"
    add_cmd_output "/usr/bin/guard -l" "$guard_log_file" "guard -l"

    add_cmd_output "echo $'\n[Guard resolved records]'" "$guard_log_file" "guard"
    add_cmd_output "/usr/bin/guard -a" "$guard_log_file" "guard -a"

    add_cmd_output "echo $'\n[Guard ephemeral records]'" "$guard_log_file" "guard"
    add_cmd_output "/usr/bin/guard -e" "$guard_log_file" "guard -e"
fi
