#!/usr/bin/env bash
#
# config: 2 25
# @brief: Collect OBMC console1 log.
#

. $DREPORT_INCLUDE/functions

desc="OBMC console1 log"
file_name="/var/log/obmc-console1.log"
if [ -e $file_name ]; then
    add_copy_file "$file_name" "$desc"
fi
