#!/usr/bin/env bash
#
# config: 234 25
# @brief: Collect PHAL devtree debug data
#

. "$DREPORT_INCLUDE/functions"

#export attributes list to attribute_list.txt
export PDBG_DTB="/var/lib/phosphor-software-manager/hostfw/running/DEVTREE"
export PDATA_INFODB="/usr/share/pdata/attributes_info.db"
attributes="/usr/bin/attributes"
file_name="PHAL_devtree.txt"
attr_cmd="$attributes export"
desc="Attribute list"
if [ -x $attributes ]; then
    add_cmd_output "$attr_cmd" "$file_name" "$desc"
fi
#copy PHAL device tree file to dump
file_name="$PDBG_DTB"
desc="Device tree file"
if [ -e "$file_name" ]; then
    add_copy_file "$file_name" "$desc"
fi

#copy PHAL export device tree to dump
file_name="/var/lib/phal/exportdevtree"
desc="Exported device tree file"
if [ -e "$file_name" ]; then
    add_copy_file "$file_name" "$desc"
fi

#copy attribues info db to dump
file_name="$PDATA_INFODB"
desc="Attribute info db"
if [ -e "$file_name" ]; then
    add_copy_file "$file_name" "$desc"
fi
