#!/usr/bin/env bash
#
# config: 234 25
# @brief: Collect PHAL devtree debug data
#

# shellcheck disable=SC1091
. "$DREPORT_INCLUDE"/functions

# shellcheck source=./power-target.sh
source /etc/profile.d/power-target.sh

#export attributes list to attribute_list.txt
attributes="/usr/bin/attributes"
file_name="PHAL_devtree.txt"
attr_cmd="$attributes export"
desc="Attribute list"
if [ -x $attributes ]; then
    add_cmd_output "$attr_cmd" "$file_name" "$desc"
fi
#copy PHAL device tree file to dump
file_name="$PDBG_DTB"
desc="Device tree file"
if [ -e "$file_name" ]; then
    add_copy_file "$file_name" "$desc"
fi

#copy PHAL export device tree to dump
file_name="/var/lib/phal/exportdevtree"
desc="Exported device tree file"
if [ -e "$file_name" ]; then
    add_copy_file "$file_name" "$desc"
fi

#copy attribues info db to dump
file_name="$PDATA_INFODB"
desc="Attribute info db"
if [ -e "$file_name" ]; then
    add_copy_file "$file_name" "$desc"
fi
