#!/bin/bash
#
# config: 1 0
# @brief: Collect Linux Kernel trace
#

# shellcheck disable=SC1091
# shellcheck disable=SC2086
. $DREPORT_INCLUDE/functions

desc="Linux Kernel trace"
file_name="/sys/kernel/tracing/trace"

add_copy_file "$file_name" "$desc"
