#!/bin/bash
#
# config: 2 20
# @brief: Get the internal dbus information.
#

# shellcheck source=/dev/null
. "$DREPORT_INCLUDE"/functions

desc="dbus internal stats"

command="timeout 5s dbus-send --system --dest=org.freedesktop.DBus \
            --type=method_call --print-reply \
            /org/freedesktop/DBus org.freedesktop.DBus.Debug.Stats.GetStats"

file_name="dbusstats.log"

add_cmd_output "$command" "$file_name" "$desc"
