#!/bin/bash
#
# config: 123 10
# @@brief: Collect failed services information
#

. $DREPORT_SOURCE/functions

desc="failed services"
file_name="failed-services.log"
command="systemctl --failed"

add_cmd_output "$command" "$file_name" "$desc"
