#!/bin/bash
#
# config: 123 10
# @brief: Collect failed services information.
#

# shellcheck source=tools/dreport.d/include.d/functions
. "$DREPORT_INCLUDE/functions"

desc="failed services"
file_name="failed-services.log"
command="systemctl --failed"

add_cmd_output "$command" "$file_name" "$desc"
