#!/bin/bash
#
# config: 2 20
# @brief: Get the fan monitor dump
#

. $DREPORT_INCLUDE/functions

if [ ! -e "/usr/bin/phosphor-fan-monitor" ]; then
  exit 0
fi

rm -f /tmp/fan_monitor_dump.json
killall -s SIGUSR1 phosphor-fan-monitor

seconds=0
while [ ! -e "/tmp/fan_monitor_dump.json" ]; do
    seconds=$(( seconds + 1 ))
    if [ $seconds -eq 5 ]; then
        echo "Timed out waiting for fan monitor dump"
        exit 0
    fi
    sleep 1
done

command="cat /tmp/fan_monitor_dump.json"
file_name="fan_monitor_dump.json"
desc="fan monitor dump"

add_cmd_output "$command" "$file_name" "$desc"

rm -rf /tmp/fan_monitor_dump.json
