#!/bin/bash
#
# config: 123 5
# @brief: Collect current hostname settings.
#

. $DREPORT_SOURCE/functions

desc="hostnamectl"
file_name="hostnamectl.log"
command="hostnamectl status"

add_cmd_output "$command" "$file_name" "$desc"
