#!/bin/bash
#
# config: 1234 5
# @brief: Collect Host state information.
#

. $DREPORT_INCLUDE/functions

desc="Host State"
file_name="host-state.log"
command="busctl get-property \
                    xyz.openbmc_project.State.Host \
                    /xyz/openbmc_project/state/host0 \
                    xyz.openbmc_project.State.Host \
                    CurrentHostState"

add_cmd_output "$command" "$file_name" "$desc"
# Discover additional BMC services for multi-host support
services=$(busctl list | awk '{print $1}' | grep "xyz.openbmc_project.State.Host\([0-9]\)$")
for service in ${services}; do
    objpath=$(busctl tree --list $service  | tail -n 1)
    index=$(echo "$service" | grep -o '[0-9]*$')
    file_name="host${index}-state.log"
    desc="Host${index} State"
    command="busctl get-property ${service} ${objpath} \
              xyz.openbmc_project.State.Host CurrentHostState"
    add_cmd_output "$command" "$file_name" "$desc"
done
