#!/bin/bash
#
# config: 2 30
# @brief: Collect ip addr information.
#

# shellcheck source=tools/dreport.d/include.d/functions
. "$DREPORT_INCLUDE/functions"

desc="ip addr"
file_name="ipaddr.log"
command="ip addr"

add_cmd_output "$command" "$file_name" "$desc"
