#!/bin/bash
#
# config: 2 30
# @brief: Collect ip link information.
#

# shellcheck source=tools/dreport.d/include.d/functions
. "$DREPORT_INCLUDE/functions"

desc="ip link"
file_name="iplink.log"
command="ip link"

add_cmd_output "$command" "$file_name" "$desc"
