#!/bin/bash
#
# config: 24 10
# @brief: Collect Journal pretty log information.
#

. $DREPORT_INCLUDE/functions

desc="Journal nopager log"
file_name="journal-nopager.log"
command="journalctl --no-pager"

add_cmd_output "$command" "$file_name" "$desc"
