#!/bin/bash
#
# config: 2 30
# @brief: Collect mount information.
#

# shellcheck source=/dev/null
. "$DREPORT_INCLUDE"/functions

desc="mount info"
file_name="mountinfo.log"
command="mount"

add_cmd_output "$command" "$file_name" "$desc"