#!/usr/bin/env bash
#
# config: 2 30
# @brief: Collect network information
#

#. $DREPORT_INCLUDE/functions

file_name="network.log"

#route
add_cmd_output "echo $'[route]'" "$file_name" "route"
add_cmd_output "route" "$file_name" "route"

#eth0
eth0_file="/etc/systemd/network/00-bmc-eth0.network"
if [ -f $eth0_file ]; then
    add_cmd_output "echo $'\n[eth0]'" "$file_name" "route"
    add_cmd_output "cat $eth0_file" "$file_name" "eth0"
fi  

#eth1
eth1_file="/etc/systemd/network/00-bmc-eth1.network"
if [ -f $eth1_file ]; then
    add_cmd_output "echo $'\n[eth1]'" "$file_name" "route"
    add_cmd_output "cat $eth1_file" "$file_name" "eth1"
fi
