#!/bin/bash
#
# config: 24 25
# @brief: Collect OBMC console log.
#

# shellcheck source=tools/dreport.d/include.d/functions
. "$DREPORT_INCLUDE/functions"

desc="OBMC console log"
file_name="/var/log/obmc-console.log"

add_copy_file "$file_name" "$desc"
