#!/bin/bash
#
# config: 12345 1
# @brief: Collect OS release information.
#

. $DREPORT_INCLUDE/functions

desc="OS release info"
file_name="/etc/os-release"

add_copy_sym_link_file "$file_name"  "$desc"

file_name="os-release"
add_backup_driver_details "$file_name"
