#!/usr/bin/env bash
#
# config: 1234 40
# @brief: Get PLDM FRU record table data
#

. $DREPORT_INCLUDE/functions

# collect data only if pldmtool is present
pldmtool="/usr/bin/pldmtool"

if [ -e $pldmtool ]; then
    desc="PLDM FRU Record table"
    file_name="pldm_fru_record_table.txt"

    add_cmd_output "$pldmtool fru getfrurecordtable" "$file_name" "$desc"
fi
