#!/usr/bin/env bash
#
# config: 234 20
# @brief: Get the settings information.
#

. "$DREPORT_INCLUDE/functions"

#fetch occ control data
file_name="settings.log"

desc="settings"
command="busctl call --verbose --no-pager \
                xyz.openbmc_project.Settings \
                / \
                org.freedesktop.DBus.ObjectManager \
                GetManagedObjects"

add_cmd_output "$command" "$file_name" "$desc"

#if busctl commands fail capture persistent data
if [ $? -ne 0 ]; then
    settings_dir="/var/lib/phosphor-settings-manager/settings"
    if [ -d "$settings_dir" ]; then
        add_copy_file "$settings_dir" "$desc"
    fi
fi
