#!/bin/bash
#
# config: 2 75
# @brief: Collect software interrupt request information.
#

# shellcheck source=tools/dreport.d/include.d/functions
. "$DREPORT_INCLUDE"/functions

desc="SoftIRQs"
file_name="softIRQs.log"
command="cat /proc/softirqs"

add_cmd_output "$command" "$file_name" "$desc"
