#!/bin/bash
#
# config: 123 50
# @brief: Collect uptime information.
#

# shellcheck source=tools/dreport.d/include.d/functions
. "$DREPORT_INCLUDE/functions"

desc="uptime"
file_name="uptime.log"
command="uptime"

add_cmd_output "$command" "$file_name" "$desc"
