#!/bin/bash

declare -rx DUMP_MANAGER='xyz.openbmc_project.Dump.Manager'
declare -rx HB_DUMP_PATH='/xyz/openbmc_project/dump/hostboot/entry'
declare -rx HW_DUMP_PATH='/xyz/openbmc_project/dump/hardware/entry'
declare -rx SBE_DUMP_PATH='/xyz/openbmc_project/dump/sbe/entry'
declare -rx DUMP_PROP='xyz.openbmc_project.Common.Progress'
declare -rx HB_DUMP='20'
declare -rx HW_DUMP='00'
declare -rx SBE_DUMP='30'

#Fetching the driver
declare -x DRIVER=$(cat /etc/os-release | grep VERSION_ID | \
    awk -F = '{ print $2}' | cut -d'(' -f 1)
declare -x YAML_FILE="$content_path/info.yaml"
declare -x ADDL_DATA_PATH="$content_path/plat_dump/additional_data/"
declare -x START_TIME=''
declare -x END_TIME=''

#Function to get the dump start and completed time
function dump_time_details() {
    if [ "$dump_content_type" = "$HB_DUMP" ]; then
        START_TIME=$(busctl get-property $DUMP_MANAGER $HB_DUMP_PATH/$dump_id \
            $DUMP_PROP StartTime | awk '{print $2}')
        END_TIME=$(busctl get-property $DUMP_MANAGER $HB_DUMP_PATH/$dump_id \
            $DUMP_PROP CompletedTime | awk '{print $2}')
    elif [ "$dump_content_type" = "$HW_DUMP" ]; then
        START_TIME=$(busctl get-property $DUMP_MANAGER $HW_DUMP_PATH/$dump_id \
            $DUMP_PROP StartTime | awk '{print $2}')
        END_TIME=$(busctl get-property $DUMP_MANAGER $HW_DUMP_PATH/$dump_id \
            $DUMP_PROP CompletedTime | awk '{print $2}')
    elif [ "$dump_content_type" = "$SBE_DUMP" ]; then
        START_TIME=$(busctl get-property $DUMP_MANAGER $SBE_DUMP_PATH/$dump_id \
            $DUMP_PROP StartTime | awk '{print $2}')
        END_TIME=$(busctl get-property $DUMP_MANAGER $SBE_DUMP_PATH/$dump_id \
            $DUMP_PROP CompletedTime | awk '{print $2}')
    fi

    if [ $? -ne 0 ]; then
        echo "Could not fetch start time for $dump_id"
        return $INTERNAL_FAILURE
    fi

    start=$(date -d @$START_TIME +'%Y-%m-%d %H:%M:%S')
    if [ $END_TIME -eq 0 ]; then
        END_TIME=$(date +"%s")
        end=$(date -d @$END_TIME +'%Y-%m-%d %H:%M:%S')
    else
        end=$(date -d @$END_TIME +'%Y-%m-%d %H:%M:%S')
    fi
    printf "dump-start-time: %s\n" "$start" >> $YAML_FILE
    printf "dump-end-time: %s\n" "$end" >> $YAML_FILE
}

#Function to fetch additional details
function get_addl_data() {
    if [ -d "$ADDL_DATA_PATH" ]; then
        for entry in "$ADDL_DATA_PATH"/*
        do
            while IFS= read -r line; do
                echo "$line" >> $YAML_FILE
            done < $entry
        done
    fi
}

#Function to write data to info.yaml file
function write_to_info_file() {
    printf "%s\n" "# SPDX-License-Identifier: GPL-2.0" >> $YAML_FILE
    printf "%s\n" "%YAML 1.2" >> $YAML_FILE
    printf "%s\n\n" "---" >> $YAML_FILE
    printf "generation: p10\n" >> $YAML_FILE
    printf "driver: %s\n" "$DRIVER" >> $YAML_FILE
    dump_time_details
    get_addl_data
}

#Run main
write_to_info_file
