#!/usr/bin/env bash

HEADER_SCRIPT="$DREPORT_INCLUDE/gendumpheader"

# @brief Packaging the dump and transferring to dump location.
function package()
{
  	mkdir -p "$dump_dir"
	if [ $? -ne 0 ]; then
	  	log_error "Could not create the destination directory $dump_dir"
		dest_dir=$TMP_DIR
	fi

	if [ -f "$HEADER_SCRIPT" ]; then
		#tar and compress the files.
		("$HEADER_SCRIPT")

		tar -Jcf "$name_dir.tar.xz" -C \
		         $(dirname "$name_dir") $(basename "$name_dir")

	    cat "$name_dir.tar.xz" | tee -a "/tmp/dumpheader" > /dev/null
		mv "/tmp/dumpheader" "$name_dir.tar.xz"
	else
	    log_error "Could not find $HEADER_SCRIPT"
	fi

	if [ $? -ne 0 ]; then
	  	echo $($TIME_STAMP) "Could not create the compressed tar file"
		rm -r "$name_dir"
		return $INTERNAL_FAILURE
	fi

	#remove the temporary name specific directory
	rm -r "$name_dir"

	echo $($TIME_STAMP) "Report is available in $dump_dir"

	if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
	  	return $SUCCESS
	fi

	#copy the compressed tar file into the destination
	cp "$name_dir.tar.xz" "$dump_dir"
	if [ $? -ne 0 ]; then
	  	echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
		rm "$name_dir.tar.xz"
		return $INTERNAL_FAILURE
	fi

	#Remove the temporary copy of the file
	rm "$name_dir.tar.xz"
}
