#!/bin/bash

# @brief Packaging the dump, applying the header
# and transferring to dump location.
function custom_package()
{
    tar -Jcf "$name_dir.bin" -C \
                 "$(dirname "$name_dir")" "$(basename "$name_dir")"
    # shellcheck disable=SC2181 # need output from `tar` in above if cond.
    if [ $? -ne 0 ]; then
        echo "$($TIME_STAMP)" "Could not create the compressed tar file"
        rm -r "$name_dir.bin"
        return "$INTERNAL_FAILURE"
    fi

    echo "Adding Dump Header :"$HEADER_EXTENSION
    ("$HEADER_EXTENSION")

    cat "$name_dir.bin" >> "/tmp/dumpheader_$EPOCHTIME"
    mv "/tmp/dumpheader_$EPOCHTIME" "$name_dir.bin"

    #remove the temporary name specific directory
    rm -r "$name_dir"

    echo "$($TIME_STAMP)" "Report is available in $dump_dir"
    if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
       return "$SUCCESS"
    fi

    #copy the compressed tar file into the destination
    cp "$name_dir.bin" "$dump_dir"

    if [ $? -ne 0 ]; then
        echo "Failed to copy the $name_dir to $dump_dir"
        rm "$name_dir.bin"
        return "$INTERNAL_FAILURE"
    fi

    #Remove the temporary copy of the file
    rm "$name_dir.bin"
}

# Executing function
custom_package
